### ISSUE TITLE
Fields "Number of keys" and "mail address" no not revalidate on change

### ISSUE THREAD

**Issue by melanietreitinger** [eledia/enrol_elediamultikeys#2]
![image2021-11-30_15-20-59](https://user-images.githubusercontent.com/66598405/145192794-c9418865-2fd2-443a-b98b-b4a79655eb7b.png)

**Comment by eledia** [comment]
I was unable to reproduce this. As soon as the submit button is hit the checks will be performed. 

Perhaps you are wondering about some checks are client and some server side. Some of the checks are client side (required fileds) some are server side (number to be greater than 0 and the email to be validated). The client side checks will be performed within the browser onchange. The server side checks will be performed only on submit. I cant make them client side. I could make the required checks server side too. But i would prefer to keep those checks client side to point out the required fields faster.
